### ISSUE TITLE
make error

### ISSUE THREAD

**Issue by hackendltd** [mav8557/Father#1]
os: centos 6.7 x86_64

[root@Father-master]# make
gcc -Wall -ldl -o rk.so -fPIC -shared -D_GNU_SOURCE father.c
father.c:128: error: conflicting types for ‘restrict’
father.c:128: note: previous definition of ‘restrict’ was here
father.c:129: error: expected ‘;’, ‘,’ or ‘)’ before ‘path’
make: *** [father] Error 1

**Comment by hackendltd** [comment]
os:centos7 elrepo kernel
[root@Father]# make
gcc -Wall -ldl -o rk.so -fPIC -shared -D_GNU_SOURCE father.c
father.c:128:51: error: conflicting types for ‘restrict’
 int (*o_lstat)(const char *restrict, struct stat *restrict);
                                                   ^
father.c:128:28: note: previous definition of ‘restrict’ was here
 int (*o_lstat)(const char *restrict, struct stat *restrict);
                            ^
father.c:129:32: error: expected ‘;’, ‘,’ or ‘)’ before ‘path’
 int lstat(const char *restrict path, struct stat *restrict buf) {
                                ^
make: *** [father] Error 1

**Comment by mav8557** [comment]
CentOS 7's shipped GCC (version 4.8.5) does not support the restrict keyword. You'll have to either remove that from the code or use a more recent GCC version.
